### ISSUE TITLE
復現流程

### ISSUE THREAD

**Issue by jcjlin** [zihengchen777/RDMS#1]
作者您好，感謝您啟發性極高的paper，想問有相關需要安裝的package (requirement)，還有整個復現流程的指南嗎，萬分感謝！

**Comment by zihengchen777** [comment]
你好，由于我在外实习，目前连不上实验室服务器，我现在所使用的电脑也没有这些环境，需要什么版本的package我也不太清楚了，很抱歉！
复现指南：将mvtec数据集放在/datasets/mvtec目录下，执行python train.py即可

**Comment by jcjlin** [comment]
了解 感謝您 實習順利!
